//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ModeloModel", "FK_Concentracion_Alumno", "Alumno", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConcentracionNotas.Models.Alumno), "Concentracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcentracionNotas.Models.Concentracion), true)]
[assembly: EdmRelationshipAttribute("ModeloModel", "FK_Asignatura_Profesor", "Profesor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConcentracionNotas.Models.Profesor), "Asignatura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcentracionNotas.Models.Asignatura), true)]
[assembly: EdmRelationshipAttribute("ModeloModel", "FK_Concentracion_Asignatura", "Asignatura", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConcentracionNotas.Models.Asignatura), "Concentracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcentracionNotas.Models.Concentracion), true)]
[assembly: EdmRelationshipAttribute("ModeloModel", "FK_Nota_Concentracion", "Concentracion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConcentracionNotas.Models.Concentracion), "Nota", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcentracionNotas.Models.Nota), true)]

#endregion

namespace ConcentracionNotas.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ModeloEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ModeloEntities usando la cadena de conexión encontrada en la sección 'ModeloEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ModeloEntities() : base("name=ModeloEntities", "ModeloEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloEntities.
        /// </summary>
        public ModeloEntities(string connectionString) : base(connectionString, "ModeloEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloEntities.
        /// </summary>
        public ModeloEntities(EntityConnection connection) : base(connection, "ModeloEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alumno> Alumno
        {
            get
            {
                if ((_Alumno == null))
                {
                    _Alumno = base.CreateObjectSet<Alumno>("Alumno");
                }
                return _Alumno;
            }
        }
        private ObjectSet<Alumno> _Alumno;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Asignatura> Asignatura
        {
            get
            {
                if ((_Asignatura == null))
                {
                    _Asignatura = base.CreateObjectSet<Asignatura>("Asignatura");
                }
                return _Asignatura;
            }
        }
        private ObjectSet<Asignatura> _Asignatura;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Concentracion> Concentracion
        {
            get
            {
                if ((_Concentracion == null))
                {
                    _Concentracion = base.CreateObjectSet<Concentracion>("Concentracion");
                }
                return _Concentracion;
            }
        }
        private ObjectSet<Concentracion> _Concentracion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Nota> Nota
        {
            get
            {
                if ((_Nota == null))
                {
                    _Nota = base.CreateObjectSet<Nota>("Nota");
                }
                return _Nota;
            }
        }
        private ObjectSet<Nota> _Nota;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Profesor> Profesor
        {
            get
            {
                if ((_Profesor == null))
                {
                    _Profesor = base.CreateObjectSet<Profesor>("Profesor");
                }
                return _Profesor;
            }
        }
        private ObjectSet<Profesor> _Profesor;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alumno. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumno(Alumno alumno)
        {
            base.AddObject("Alumno", alumno);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Asignatura. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAsignatura(Asignatura asignatura)
        {
            base.AddObject("Asignatura", asignatura);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Concentracion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToConcentracion(Concentracion concentracion)
        {
            base.AddObject("Concentracion", concentracion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Nota. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNota(Nota nota)
        {
            base.AddObject("Nota", nota);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Profesor. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProfesor(Profesor profesor)
        {
            base.AddObject("Profesor", profesor);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloModel", Name="Alumno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alumno : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alumno.
        /// </summary>
        /// <param name="alumnoId">Valor inicial de la propiedad AlumnoId.</param>
        /// <param name="alumnoRut">Valor inicial de la propiedad AlumnoRut.</param>
        /// <param name="alumnoRutDigito">Valor inicial de la propiedad AlumnoRutDigito.</param>
        /// <param name="alumnoNombre">Valor inicial de la propiedad AlumnoNombre.</param>
        /// <param name="alumnoApellido">Valor inicial de la propiedad AlumnoApellido.</param>
        public static Alumno CreateAlumno(global::System.Int32 alumnoId, global::System.Int32 alumnoRut, global::System.String alumnoRutDigito, global::System.String alumnoNombre, global::System.String alumnoApellido)
        {
            Alumno alumno = new Alumno();
            alumno.AlumnoId = alumnoId;
            alumno.AlumnoRut = alumnoRut;
            alumno.AlumnoRutDigito = alumnoRutDigito;
            alumno.AlumnoNombre = alumnoNombre;
            alumno.AlumnoApellido = alumnoApellido;
            return alumno;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlumnoId
        {
            get
            {
                return _AlumnoId;
            }
            set
            {
                if (_AlumnoId != value)
                {
                    OnAlumnoIdChanging(value);
                    ReportPropertyChanging("AlumnoId");
                    _AlumnoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AlumnoId");
                    OnAlumnoIdChanged();
                }
            }
        }
        private global::System.Int32 _AlumnoId;
        partial void OnAlumnoIdChanging(global::System.Int32 value);
        partial void OnAlumnoIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlumnoRut
        {
            get
            {
                return _AlumnoRut;
            }
            set
            {
                OnAlumnoRutChanging(value);
                ReportPropertyChanging("AlumnoRut");
                _AlumnoRut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlumnoRut");
                OnAlumnoRutChanged();
            }
        }
        private global::System.Int32 _AlumnoRut;
        partial void OnAlumnoRutChanging(global::System.Int32 value);
        partial void OnAlumnoRutChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AlumnoRutDigito
        {
            get
            {
                return _AlumnoRutDigito;
            }
            set
            {
                OnAlumnoRutDigitoChanging(value);
                ReportPropertyChanging("AlumnoRutDigito");
                _AlumnoRutDigito = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AlumnoRutDigito");
                OnAlumnoRutDigitoChanged();
            }
        }
        private global::System.String _AlumnoRutDigito;
        partial void OnAlumnoRutDigitoChanging(global::System.String value);
        partial void OnAlumnoRutDigitoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AlumnoNombre
        {
            get
            {
                return _AlumnoNombre;
            }
            set
            {
                OnAlumnoNombreChanging(value);
                ReportPropertyChanging("AlumnoNombre");
                _AlumnoNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AlumnoNombre");
                OnAlumnoNombreChanged();
            }
        }
        private global::System.String _AlumnoNombre;
        partial void OnAlumnoNombreChanging(global::System.String value);
        partial void OnAlumnoNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AlumnoApellido
        {
            get
            {
                return _AlumnoApellido;
            }
            set
            {
                OnAlumnoApellidoChanging(value);
                ReportPropertyChanging("AlumnoApellido");
                _AlumnoApellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AlumnoApellido");
                OnAlumnoApellidoChanged();
            }
        }
        private global::System.String _AlumnoApellido;
        partial void OnAlumnoApellidoChanging(global::System.String value);
        partial void OnAlumnoApellidoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Concentracion_Alumno", "Concentracion")]
        public EntityCollection<Concentracion> Concentracion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Concentracion>("ModeloModel.FK_Concentracion_Alumno", "Concentracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Concentracion>("ModeloModel.FK_Concentracion_Alumno", "Concentracion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloModel", Name="Asignatura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Asignatura : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Asignatura.
        /// </summary>
        /// <param name="asignaturaId">Valor inicial de la propiedad AsignaturaId.</param>
        /// <param name="profesorId">Valor inicial de la propiedad ProfesorId.</param>
        /// <param name="asignaturaNombre">Valor inicial de la propiedad AsignaturaNombre.</param>
        /// <param name="asignaturaTipo">Valor inicial de la propiedad AsignaturaTipo.</param>
        public static Asignatura CreateAsignatura(global::System.Int32 asignaturaId, global::System.Int32 profesorId, global::System.String asignaturaNombre, global::System.Int16 asignaturaTipo)
        {
            Asignatura asignatura = new Asignatura();
            asignatura.AsignaturaId = asignaturaId;
            asignatura.ProfesorId = profesorId;
            asignatura.AsignaturaNombre = asignaturaNombre;
            asignatura.AsignaturaTipo = asignaturaTipo;
            return asignatura;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AsignaturaId
        {
            get
            {
                return _AsignaturaId;
            }
            set
            {
                if (_AsignaturaId != value)
                {
                    OnAsignaturaIdChanging(value);
                    ReportPropertyChanging("AsignaturaId");
                    _AsignaturaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AsignaturaId");
                    OnAsignaturaIdChanged();
                }
            }
        }
        private global::System.Int32 _AsignaturaId;
        partial void OnAsignaturaIdChanging(global::System.Int32 value);
        partial void OnAsignaturaIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfesorId
        {
            get
            {
                return _ProfesorId;
            }
            set
            {
                OnProfesorIdChanging(value);
                ReportPropertyChanging("ProfesorId");
                _ProfesorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfesorId");
                OnProfesorIdChanged();
            }
        }
        private global::System.Int32 _ProfesorId;
        partial void OnProfesorIdChanging(global::System.Int32 value);
        partial void OnProfesorIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AsignaturaNombre
        {
            get
            {
                return _AsignaturaNombre;
            }
            set
            {
                OnAsignaturaNombreChanging(value);
                ReportPropertyChanging("AsignaturaNombre");
                _AsignaturaNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AsignaturaNombre");
                OnAsignaturaNombreChanged();
            }
        }
        private global::System.String _AsignaturaNombre;
        partial void OnAsignaturaNombreChanging(global::System.String value);
        partial void OnAsignaturaNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 AsignaturaTipo
        {
            get
            {
                return _AsignaturaTipo;
            }
            set
            {
                OnAsignaturaTipoChanging(value);
                ReportPropertyChanging("AsignaturaTipo");
                _AsignaturaTipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AsignaturaTipo");
                OnAsignaturaTipoChanged();
            }
        }
        private global::System.Int16 _AsignaturaTipo;
        partial void OnAsignaturaTipoChanging(global::System.Int16 value);
        partial void OnAsignaturaTipoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Asignatura_Profesor", "Profesor")]
        public Profesor Profesor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("ModeloModel.FK_Asignatura_Profesor", "Profesor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("ModeloModel.FK_Asignatura_Profesor", "Profesor").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profesor> ProfesorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("ModeloModel.FK_Asignatura_Profesor", "Profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profesor>("ModeloModel.FK_Asignatura_Profesor", "Profesor", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Concentracion_Asignatura", "Concentracion")]
        public EntityCollection<Concentracion> Concentracion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Concentracion>("ModeloModel.FK_Concentracion_Asignatura", "Concentracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Concentracion>("ModeloModel.FK_Concentracion_Asignatura", "Concentracion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloModel", Name="Concentracion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Concentracion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Concentracion.
        /// </summary>
        /// <param name="concentFolio">Valor inicial de la propiedad ConcentFolio.</param>
        /// <param name="asignaturaId">Valor inicial de la propiedad AsignaturaId.</param>
        /// <param name="alumnoId">Valor inicial de la propiedad AlumnoId.</param>
        /// <param name="concentSituacion">Valor inicial de la propiedad ConcentSituacion.</param>
        public static Concentracion CreateConcentracion(global::System.Int32 concentFolio, global::System.Int32 asignaturaId, global::System.Int32 alumnoId, global::System.Int16 concentSituacion)
        {
            Concentracion concentracion = new Concentracion();
            concentracion.ConcentFolio = concentFolio;
            concentracion.AsignaturaId = asignaturaId;
            concentracion.AlumnoId = alumnoId;
            concentracion.ConcentSituacion = concentSituacion;
            return concentracion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConcentFolio
        {
            get
            {
                return _ConcentFolio;
            }
            set
            {
                if (_ConcentFolio != value)
                {
                    OnConcentFolioChanging(value);
                    ReportPropertyChanging("ConcentFolio");
                    _ConcentFolio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConcentFolio");
                    OnConcentFolioChanged();
                }
            }
        }
        private global::System.Int32 _ConcentFolio;
        partial void OnConcentFolioChanging(global::System.Int32 value);
        partial void OnConcentFolioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AsignaturaId
        {
            get
            {
                return _AsignaturaId;
            }
            set
            {
                OnAsignaturaIdChanging(value);
                ReportPropertyChanging("AsignaturaId");
                _AsignaturaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AsignaturaId");
                OnAsignaturaIdChanged();
            }
        }
        private global::System.Int32 _AsignaturaId;
        partial void OnAsignaturaIdChanging(global::System.Int32 value);
        partial void OnAsignaturaIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlumnoId
        {
            get
            {
                return _AlumnoId;
            }
            set
            {
                OnAlumnoIdChanging(value);
                ReportPropertyChanging("AlumnoId");
                _AlumnoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlumnoId");
                OnAlumnoIdChanged();
            }
        }
        private global::System.Int32 _AlumnoId;
        partial void OnAlumnoIdChanging(global::System.Int32 value);
        partial void OnAlumnoIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ConcentPromedio
        {
            get
            {
                return _ConcentPromedio;
            }
            set
            {
                OnConcentPromedioChanging(value);
                ReportPropertyChanging("ConcentPromedio");
                _ConcentPromedio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConcentPromedio");
                OnConcentPromedioChanged();
            }
        }
        private Nullable<global::System.Decimal> _ConcentPromedio;
        partial void OnConcentPromedioChanging(Nullable<global::System.Decimal> value);
        partial void OnConcentPromedioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ConcentSituacion
        {
            get
            {
                return _ConcentSituacion;
            }
            set
            {
                OnConcentSituacionChanging(value);
                ReportPropertyChanging("ConcentSituacion");
                _ConcentSituacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConcentSituacion");
                OnConcentSituacionChanged();
            }
        }
        private global::System.Int16 _ConcentSituacion;
        partial void OnConcentSituacionChanging(global::System.Int16 value);
        partial void OnConcentSituacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ConcentAsistencia
        {
            get
            {
                return _ConcentAsistencia;
            }
            set
            {
                OnConcentAsistenciaChanging(value);
                ReportPropertyChanging("ConcentAsistencia");
                _ConcentAsistencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConcentAsistencia");
                OnConcentAsistenciaChanged();
            }
        }
        private Nullable<global::System.Int16> _ConcentAsistencia;
        partial void OnConcentAsistenciaChanging(Nullable<global::System.Int16> value);
        partial void OnConcentAsistenciaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Concentracion_Alumno", "Alumno")]
        public Alumno Alumno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alumno>("ModeloModel.FK_Concentracion_Alumno", "Alumno").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alumno>("ModeloModel.FK_Concentracion_Alumno", "Alumno").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Alumno> AlumnoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alumno>("ModeloModel.FK_Concentracion_Alumno", "Alumno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Alumno>("ModeloModel.FK_Concentracion_Alumno", "Alumno", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Concentracion_Asignatura", "Asignatura")]
        public Asignatura Asignatura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Asignatura>("ModeloModel.FK_Concentracion_Asignatura", "Asignatura").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Asignatura>("ModeloModel.FK_Concentracion_Asignatura", "Asignatura").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Asignatura> AsignaturaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Asignatura>("ModeloModel.FK_Concentracion_Asignatura", "Asignatura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Asignatura>("ModeloModel.FK_Concentracion_Asignatura", "Asignatura", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Nota_Concentracion", "Nota")]
        public EntityCollection<Nota> Nota
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Nota>("ModeloModel.FK_Nota_Concentracion", "Nota");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Nota>("ModeloModel.FK_Nota_Concentracion", "Nota", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloModel", Name="Nota")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Nota : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Nota.
        /// </summary>
        /// <param name="notaId">Valor inicial de la propiedad NotaId.</param>
        /// <param name="concentFolio">Valor inicial de la propiedad ConcentFolio.</param>
        /// <param name="notaNumero">Valor inicial de la propiedad NotaNumero.</param>
        /// <param name="notaPonderacion">Valor inicial de la propiedad NotaPonderacion.</param>
        public static Nota CreateNota(global::System.Int32 notaId, global::System.Int32 concentFolio, global::System.Int16 notaNumero, global::System.Int16 notaPonderacion)
        {
            Nota nota = new Nota();
            nota.NotaId = notaId;
            nota.ConcentFolio = concentFolio;
            nota.NotaNumero = notaNumero;
            nota.NotaPonderacion = notaPonderacion;
            return nota;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NotaId
        {
            get
            {
                return _NotaId;
            }
            set
            {
                if (_NotaId != value)
                {
                    OnNotaIdChanging(value);
                    ReportPropertyChanging("NotaId");
                    _NotaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NotaId");
                    OnNotaIdChanged();
                }
            }
        }
        private global::System.Int32 _NotaId;
        partial void OnNotaIdChanging(global::System.Int32 value);
        partial void OnNotaIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConcentFolio
        {
            get
            {
                return _ConcentFolio;
            }
            set
            {
                OnConcentFolioChanging(value);
                ReportPropertyChanging("ConcentFolio");
                _ConcentFolio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConcentFolio");
                OnConcentFolioChanged();
            }
        }
        private global::System.Int32 _ConcentFolio;
        partial void OnConcentFolioChanging(global::System.Int32 value);
        partial void OnConcentFolioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 NotaNumero
        {
            get
            {
                return _NotaNumero;
            }
            set
            {
                OnNotaNumeroChanging(value);
                ReportPropertyChanging("NotaNumero");
                _NotaNumero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotaNumero");
                OnNotaNumeroChanged();
            }
        }
        private global::System.Int16 _NotaNumero;
        partial void OnNotaNumeroChanging(global::System.Int16 value);
        partial void OnNotaNumeroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 NotaPonderacion
        {
            get
            {
                return _NotaPonderacion;
            }
            set
            {
                OnNotaPonderacionChanging(value);
                ReportPropertyChanging("NotaPonderacion");
                _NotaPonderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotaPonderacion");
                OnNotaPonderacionChanged();
            }
        }
        private global::System.Int16 _NotaPonderacion;
        partial void OnNotaPonderacionChanging(global::System.Int16 value);
        partial void OnNotaPonderacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NotaObtenido
        {
            get
            {
                return _NotaObtenido;
            }
            set
            {
                OnNotaObtenidoChanging(value);
                ReportPropertyChanging("NotaObtenido");
                _NotaObtenido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotaObtenido");
                OnNotaObtenidoChanged();
            }
        }
        private Nullable<global::System.Decimal> _NotaObtenido;
        partial void OnNotaObtenidoChanging(Nullable<global::System.Decimal> value);
        partial void OnNotaObtenidoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Nota_Concentracion", "Concentracion")]
        public Concentracion Concentracion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concentracion>("ModeloModel.FK_Nota_Concentracion", "Concentracion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concentracion>("ModeloModel.FK_Nota_Concentracion", "Concentracion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Concentracion> ConcentracionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concentracion>("ModeloModel.FK_Nota_Concentracion", "Concentracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Concentracion>("ModeloModel.FK_Nota_Concentracion", "Concentracion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloModel", Name="Profesor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profesor : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Profesor.
        /// </summary>
        /// <param name="profesorId">Valor inicial de la propiedad ProfesorId.</param>
        /// <param name="profesorRutDigito">Valor inicial de la propiedad ProfesorRutDigito.</param>
        /// <param name="profesorNombre">Valor inicial de la propiedad ProfesorNombre.</param>
        /// <param name="profesorApellido">Valor inicial de la propiedad ProfesorApellido.</param>
        public static Profesor CreateProfesor(global::System.Int32 profesorId, global::System.String profesorRutDigito, global::System.String profesorNombre, global::System.String profesorApellido)
        {
            Profesor profesor = new Profesor();
            profesor.ProfesorId = profesorId;
            profesor.ProfesorRutDigito = profesorRutDigito;
            profesor.ProfesorNombre = profesorNombre;
            profesor.ProfesorApellido = profesorApellido;
            return profesor;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfesorId
        {
            get
            {
                return _ProfesorId;
            }
            set
            {
                if (_ProfesorId != value)
                {
                    OnProfesorIdChanging(value);
                    ReportPropertyChanging("ProfesorId");
                    _ProfesorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProfesorId");
                    OnProfesorIdChanged();
                }
            }
        }
        private global::System.Int32 _ProfesorId;
        partial void OnProfesorIdChanging(global::System.Int32 value);
        partial void OnProfesorIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProfesorRut
        {
            get
            {
                return _ProfesorRut;
            }
            set
            {
                OnProfesorRutChanging(value);
                ReportPropertyChanging("ProfesorRut");
                _ProfesorRut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfesorRut");
                OnProfesorRutChanged();
            }
        }
        private Nullable<global::System.Int32> _ProfesorRut;
        partial void OnProfesorRutChanging(Nullable<global::System.Int32> value);
        partial void OnProfesorRutChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProfesorRutDigito
        {
            get
            {
                return _ProfesorRutDigito;
            }
            set
            {
                OnProfesorRutDigitoChanging(value);
                ReportPropertyChanging("ProfesorRutDigito");
                _ProfesorRutDigito = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProfesorRutDigito");
                OnProfesorRutDigitoChanged();
            }
        }
        private global::System.String _ProfesorRutDigito;
        partial void OnProfesorRutDigitoChanging(global::System.String value);
        partial void OnProfesorRutDigitoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProfesorNombre
        {
            get
            {
                return _ProfesorNombre;
            }
            set
            {
                OnProfesorNombreChanging(value);
                ReportPropertyChanging("ProfesorNombre");
                _ProfesorNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProfesorNombre");
                OnProfesorNombreChanged();
            }
        }
        private global::System.String _ProfesorNombre;
        partial void OnProfesorNombreChanging(global::System.String value);
        partial void OnProfesorNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProfesorApellido
        {
            get
            {
                return _ProfesorApellido;
            }
            set
            {
                OnProfesorApellidoChanging(value);
                ReportPropertyChanging("ProfesorApellido");
                _ProfesorApellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProfesorApellido");
                OnProfesorApellidoChanged();
            }
        }
        private global::System.String _ProfesorApellido;
        partial void OnProfesorApellidoChanging(global::System.String value);
        partial void OnProfesorApellidoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloModel", "FK_Asignatura_Profesor", "Asignatura")]
        public EntityCollection<Asignatura> Asignatura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Asignatura>("ModeloModel.FK_Asignatura_Profesor", "Asignatura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Asignatura>("ModeloModel.FK_Asignatura_Profesor", "Asignatura", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
